includes:
- configs/ss02/defaults.yaml

setup:
  Lx: 12
  Tx: 3 ## should be the same as freq ratio
  Ty: 4 ## lag = Ty - 1
  freq_ratio: 3
  bidirectional_encoder: False
  model_type: 'MTMFSeq2Seq'
  
train:
  n_a: 768
  n_s: 256
  n_align_x: 64
  n_align_y: 64
  fc_x: 900
  fc_y: 128
  dropout_rate: 0.1
  l1reg: 0.0001
  l2reg: 0.0001
  learning_rate: 0.0001
  reduce_LR_factor: 0.5
  reduce_LR_patience: 10
