includes:
- configs/electricity/defaults.yaml

setup:
  Lx: 48 ## lag_x
  Ty: 8  ## equivalent to Ly + 1
  Tx: 1
  model_type: 'GBM'
  
hyper_params_x:
  objective: 'regression'
  boosting_type: 'gbdt'
  num_leaves: 31
  learning_rate: 0.05
  n_estimators: 200
  min_child_samples: 10
  feature_fraction: 0.8
  verbose: -1
  metric: 'l2'
  early_stopping_round: 50

hyper_params_y:
  objective: 'regression'
  boosting_type: 'gbdt'
  num_leaves: 31
  learning_rate: 0.05
  n_estimators: 200
  min_child_samples: 10
  feature_fraction: 0.8
  verbose: -1
  metric: 'l2'
  early_stopping_round: 50
