includes:
- configs/ss00/defaults.yaml

setup:
  Lx: 24
  Tx: 12
  Ly: 8
  Ty: 4
  freq_ratio: 3
  model_type: 'DeepAR'

run_params:
  scale_data: False
  batch_size: 32
  learning_rate: 0.005
  epochs: 100
  ES_patience: 30
  gradient_clip: 0.5
  enable_progress_bar: False

hyper_params:
  n_rnn_layers: 2
  hidden_dim: 256
  dropout_rate: 0.1
  reduce_on_plateau_patience: 5
  reduce_on_plateau_factor: 0.5
